# Generated by Django 6.0.4 on 2026-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
